ALTER TABLE "Student"
ADD COLUMN "petName" TEXT NOT NULL DEFAULT '小码兽',
ADD COLUMN "petSpecies" TEXT NOT NULL DEFAULT '云朵龙',
ADD COLUMN "petXp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "petMood" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "petEnergy" INTEGER NOT NULL DEFAULT 100;

UPDATE "Student"
SET "petXp" = "xp"
WHERE "petXp" = 0 AND "xp" > 0;
